language: node_js

node_js:
  - stable

script:
  - npm run test
  - npm run build

before_install:
  - npm install

after_success: 
  - npm run coverage

deploy:
  provider: npm
  email: "418022698@qq.com"
  api_key: $NPM_TOKEN
  skip_cleanup: true
  on:
    tags: true

cache: npm